### ISSUE TITLE
using Mux throws an error on 0.4

### ISSUE THREAD

**Issue by amitmurthy** [JunoLab/Mux.jl#2]
```
ERROR: LoadError: LoadError: UndefVarError: @errs not defined
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:51
while loading /home/amitm/.julia/v0.4/Mux/src/server.jl, in expression starting on line 46
while loading /home/amitm/.julia/v0.4/Mux/src/Mux.jl, in expression starting on line 22
```

**Comment by one-more-minute** [comment]
This particular error is happening because you need to `Pkg.checkout("Lazy")`. (I'll tag a release soon to fix that.) On my system using Mux on 0.4 still fails due to an issue with BinDeps, but I have no idea if that'll happen on Linux.

**Comment by shashi** [comment]
Bump. You should tag Lazy!

**Comment by one-more-minute** [comment]
I think I tagged a release for Escher a while back, right? Not sure if 0.4 is working yet though as the HTTP stack might still be broken.

(I can't actually test this right now as Pkg keeps hanging on me, no idea why)

**Comment by shashi** [comment]
Hmm, I might have not run Pkg.update(). Thanks! Anyway, Escher can't work on v0.4 until https://github.com/JuliaWeb/GnuTLS.jl/issues/45 is resolved.

**Comment by jiahao** [comment]
bump?

**Comment by one-more-minute** [comment]
This seems to be fixed up on master. I'll tag releases of everything ASAP.
