### ISSUE TITLE
Ambiguity warning in div method

### ISSUE THREAD

**Issue by jiahao** [JunoLab/Mux.jl#9]
In `examples/files.jl`, for example, constructing an HTML `div` element throws a warning on 0.4:

```
Warning: both Hiccup and Base export "div"; uses of it in module Mux must be qualified
```

**Comment by jiahao** [comment]
Looks like e3c6950 is sufficient to fix this issue.

**Comment by one-more-minute** [comment]
I think that's everything, I just need to register MacroTools. Let me know if there's anything else I can do to help out.
